// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9inGMHcKZzgMHMZp7Y2g_C8D_JgHBwKs',
    appId: '1:773404912680:web:23b758604382054a3ed91d',
    messagingSenderId: '773404912680',
    projectId: 'twin-finder-bb4ac',
    authDomain: 'twin-finder-bb4ac.firebaseapp.com',
    storageBucket: 'twin-finder-bb4ac.firebasestorage.app',
    measurementId: 'G-9HQ90NJ6QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBELevNpWPc4LPFd3k1XogJm4-yl8bAAGM',
    appId: '1:773404912680:android:b76b8ce9c04494643ed91d',
    messagingSenderId: '773404912680',
    projectId: 'twin-finder-bb4ac',
    storageBucket: 'twin-finder-bb4ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh1UhZEk6U9om1fnXMitQJCK8Osqta_OE',
    appId: '1:773404912680:ios:76c71c9bf3d148ff3ed91d',
    messagingSenderId: '773404912680',
    projectId: 'twin-finder-bb4ac',
    storageBucket: 'twin-finder-bb4ac.firebasestorage.app',
    androidClientId: '773404912680-nc75ggos52okapgo830akl4pnakt83hs.apps.googleusercontent.com',
    iosClientId: '773404912680-594f0rmf4nfj1g8cp3m2k8jogo8d2s07.apps.googleusercontent.com',
    iosBundleId: 'app.twin.finder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh1UhZEk6U9om1fnXMitQJCK8Osqta_OE',
    appId: '1:773404912680:ios:478b6b21e7c54c233ed91d',
    messagingSenderId: '773404912680',
    projectId: 'twin-finder-bb4ac',
    storageBucket: 'twin-finder-bb4ac.firebasestorage.app',
    androidClientId: '773404912680-nc75ggos52okapgo830akl4pnakt83hs.apps.googleusercontent.com',
    iosClientId: '773404912680-kf2t7brlhah4jpfg5nuvesh7k2lk0qi8.apps.googleusercontent.com',
    iosBundleId: 'com.example.twinFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9inGMHcKZzgMHMZp7Y2g_C8D_JgHBwKs',
    appId: '1:773404912680:web:21c772db786047a23ed91d',
    messagingSenderId: '773404912680',
    projectId: 'twin-finder-bb4ac',
    authDomain: 'twin-finder-bb4ac.firebaseapp.com',
    storageBucket: 'twin-finder-bb4ac.firebasestorage.app',
    measurementId: 'G-RL8RS5X9X5',
  );
}
